filename:
    wiki_file       : "wiki"
    standard_file   : "standard"
    part_file       : "part"

dump:
    standard_file   : on
    part_file       : on

filter:
    length:
        len_min : 10
        len_max : 20
    dump:
        noun_main       : on
        noun_sub        : on
        verb_main       : on
        verb_sub        : on
        adjective_main  : on
        adjective_sub   : on
        adverb          : on
        particle        : on
        auxiliary_verb  : on
        conjunction     : on
        prefix          : on
        filler          : on
        impression_verb : on
        three_dots      : on
        phrase_point    : on
        reading_point   : on
        other           : on
    exist:
        noun_main       : on
        noun_sub        : off
        verb_main       : off
        verb_sub        : off
        adjective_main  : off
        adjective_sub   : off
        adverb          : off
        particle        : off
        auxiliary_verb  : off
        conjunction     : off
        prefix          : off
        filler          : off
        impression_verb : off
        three_dots      : off
        phrase_point    : off
        reading_point   : off

part:
    noun_main       : "自立名詞"
    noun_sub        : "非自立名詞"
    verb_main       : "自立動詞"
    verb_sub        : "非自立動詞"
    adjective_main  : "自立形容詞"
    adjective_sub   : "非自立形容詞"
    adverb          : "副詞"
    particle        : "助詞"
    auxiliary_verb  : "助動詞"
    conjunction     : "接続詞"
    prefix          : "接頭詞"
    filler          : "フィラー"
    impression_verb : "感動詞"
    three_dots      : "ドット"
    phrase_point    : "句点"
    reading_point   : "読点"
    other           : "その他"
